### ISSUE TITLE
PNPM error | not present on Yarn or NPM

### ISSUE THREAD

**Issue by SanderCokart** [protonemedia/laravel-splade#207]
# Error
So deleting the lock file of a fresh splade app and running pnpm install && pnpm run build for SSR results in the following error:

# Note
pnpm dev works absolutely fine.

```bash
[vite]: Rollup failed to resolve import "@vue/server-renderer" from "resources/js/ssr.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@vue/server-renderer" from "resources/js/ssr.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///D:/Projects/learning-splade/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
    at onwarn (file:///D:/Projects/learning-splade/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
    at Object.onwarn (file:///D:/Projects/learning-splade/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///D:/Projects/learning-splade/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///D:/Projects/learning-splade/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pascalbaljet** [comment]
Does it work with `npm` or `yarn`, or does it specifically break with `pnpm`?

**Comment by SanderCokart** [comment]
Yes yarn and npm can excecute `build` totally fine.
