### ISSUE TITLE
Filepond multiple fille upload broken

### ISSUE THREAD

**Issue by bardolf69** [protonemedia/laravel-splade#475]
- Laravel Version: 10.14.1
- PHP Version: 8.1.17
- Splade JS Version (npm): 1.4.15
- Splade PHP Version (composer): 1.4.15.1
- Dev environment (OS, Sail/Valet/etc): Alpine linux running in a docker container on Google Cloud Run

### Description:

Unable to use filepond multiple as it results in a script error
```
protone-media-laravel-splade.js:4196 Uncaught TypeError: t.push is not a function
    at protone-media-laravel-splade.js:4196:13
    at Array.forEach (<anonymous>)
    at Proxy.addFiles (protone-media-laravel-splade.js:4195:11)
    at onaddfile (protone-media-laravel-splade.js:4119:106)
    at exposeEvent (filepond.esm.js:8867:13)
    at filepond.esm.js:8883:29
```

### Steps To Reproduce Issue:

Use a file upload set for filepond and multiple as below.

```
<x-splade-file class="py-4" name="css" multiple filepond accept="text/css, text/plain" />
```

**Comment by am0nn** [comment]
same issue here, do you solved it yet?

**Comment by bardolf69** [comment]
no as a work around I have just stopped using the filepond for multiple uploads

**Comment by pascalbaljet** [comment]
You need to pass the name as an array (`css[]`):

```blade
<x-splade-file class="py-4" name="css[]" multiple filepond accept="text/css, text/plain" />
```
